env:
  browser: true
  es2021: true
  react-native/react-native: true
extends:
  - plugin:react/recommended
  - plugin:react-native/all
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-native
rules: {}
